[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
coredao_sepolia = "${COREDAO_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
coredao_sepolia = { key = "${COREDAO_API_KEY}", url = "https://api-sepolia.explorer.coredao.org/api" }